-- Database setup script for Rate My Landlord
-- This script sets up the tables, sequences, RLS policies, storage bucket, and seed data.

-- 1. Create admins table
CREATE TABLE IF NOT EXISTS public.admins (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  email text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admins_pkey PRIMARY KEY (id)
);

-- 2. Create landlords table
-- NOTE: `city` is the landlord's PRIMARY city (kept for backward-compat).
-- `cities` is the full set of cities where the landlord has properties — a
-- single landlord can own/manage properties across multiple cities. When
-- `cities` is empty the app falls back to [city] (see utils/landlord.ts).
CREATE TABLE IF NOT EXISTS public.landlords (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  city text NOT NULL,
  cities text[] DEFAULT '{}'::text[], -- all cities this landlord operates in (may span multiple)
  addresses text[] DEFAULT '{}'::text[],
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  is_deleted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT landlords_pkey PRIMARY KEY (id)
);

-- ===========================================================================
-- MIGRATION (run this on an EXISTING database that predates the `cities`
-- column / multi-city support). Safe to run once; skip on a fresh install
-- since the CREATE TABLE above already includes `cities`.
--
--   -- a) Add the new column
--   ALTER TABLE public.landlords
--     ADD COLUMN IF NOT EXISTS cities text[] DEFAULT '{}'::text[];
--
--   -- b) Backfill it from the existing single `city` value
--   UPDATE public.landlords
--     SET cities = ARRAY[city]
--     WHERE (cities IS NULL OR cardinality(cities) = 0) AND city IS NOT NULL;
--
--   -- c) Index for fast "landlords in city X" lookups (array containment)
--   CREATE INDEX IF NOT EXISTS idx_landlords_cities
--     ON public.landlords USING GIN (cities) WHERE NOT is_deleted;
--
-- To query landlords in a given city against the array column:
--   SELECT * FROM public.landlords WHERE cities @> ARRAY['Cleveland, OH'];
-- ===========================================================================

-- 3. Create reviews table
CREATE TABLE IF NOT EXISTS public.reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  landlord_id bigint NOT NULL,
  user_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  communication integer NOT NULL CHECK (communication >= 1 AND communication <= 5),
  maintenance integer NOT NULL CHECK (maintenance >= 1 AND maintenance <= 5),
  respect integer NOT NULL CHECK (respect >= 1 AND respect <= 5),
  comment text NOT NULL,
  rent_amount numeric,
  property_address text,
  verification_file_url text,
  would_rent_again boolean DEFAULT false,
  verification_status text DEFAULT 'unverified'::text CHECK (verification_status = ANY (ARRAY['unverified'::text, 'pending'::text, 'verified'::text])),
  is_deleted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by_student boolean DEFAULT false,
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_landlord_id_fkey FOREIGN KEY (landlord_id) REFERENCES public.landlords(id) ON DELETE CASCADE,
  CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL
);

-- 4. Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_landlords_city ON public.landlords(city) WHERE NOT is_deleted;
-- GIN index supports fast "landlords in city X" lookups against the cities array:
--   SELECT * FROM public.landlords WHERE cities @> ARRAY['Cleveland, OH'];
CREATE INDEX IF NOT EXISTS idx_landlords_cities ON public.landlords USING GIN (cities) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS idx_landlords_status ON public.landlords(status) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS idx_reviews_landlord_id ON public.reviews(landlord_id) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS idx_reviews_user_id ON public.reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_verification_status ON public.reviews(verification_status) WHERE NOT is_deleted;

-- 5. Trigger for updated_at on reviews table
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trigger_reviews_updated_at
  BEFORE UPDATE ON public.reviews
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_updated_at();

-- 5b. Dynamic city tracking
-- The app does NOT keep a hard-coded list of cities. Instead it asks the
-- backend for the distinct set of cities that currently have a landlord, and
-- that set grows automatically as people add landlords anywhere in the US.
-- The frontend calls this via supabase.rpc('get_cities').
CREATE OR REPLACE FUNCTION public.get_cities()
RETURNS TABLE (city text)
LANGUAGE sql STABLE AS $$
  SELECT DISTINCT c AS city
  FROM public.landlords l,
       LATERAL unnest(
         CASE WHEN cardinality(l.cities) > 0 THEN l.cities ELSE ARRAY[l.city] END
       ) AS c
  WHERE NOT l.is_deleted AND l.status = 'approved' AND c IS NOT NULL AND c <> ''
  ORDER BY city;
$$;

-- The GIN index on `cities` (section 4) already keeps the per-city landlord
-- lookups fast. The DISTINCT above is fine up to fairly large tables.
--
-- ===========================================================================
-- OPTIONAL — for very large datasets, replace the DISTINCT scan with a
-- maintained lookup table so get_cities() is an O(rows-in-cities-table) read:
--
--   CREATE TABLE IF NOT EXISTS public.cities (
--     name text PRIMARY KEY,           -- canonical "City, ST"
--     landlord_count integer NOT NULL DEFAULT 0
--   );
--
--   -- Keep it in sync from a trigger on landlords (insert/update/delete),
--   -- incrementing/decrementing landlord_count per city in NEW.cities /
--   -- OLD.cities, and deleting rows whose count hits 0. Then:
--   --   SELECT name FROM public.cities WHERE landlord_count > 0 ORDER BY name;
--   --
--   -- Normalization/dedup of spellings (casing, "St." vs "St", same-name
--   -- different-state) is done in the app before insert (see utils/cities.ts:
--   -- buildCity + reconcileCity) so this table stays clean.
-- ===========================================================================

-- 6. Helper function to check if the current user is an admin
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean SECURITY DEFINER AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.admins
    WHERE email = auth.jwt() ->> 'email'
  );
END;
$$ LANGUAGE plpgsql;

-- 7. Enable Row Level Security (RLS)
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.landlords ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- 8. Row Level Security policies

-- Admins Table Policies
CREATE POLICY "Anyone can view admins" ON public.admins
  FOR SELECT TO public USING (true);

-- Landlords Table Policies
CREATE POLICY "Admins can update landlords" ON public.landlords
  FOR UPDATE TO public USING (public.is_admin());

CREATE POLICY "Admins can view all landlords" ON public.landlords
  FOR SELECT TO public USING (public.is_admin());

CREATE POLICY "Authenticated users can insert landlords" ON public.landlords
  FOR INSERT TO public WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Everyone can view approved landlords" ON public.landlords
  FOR SELECT TO public USING (status = 'approved' AND NOT is_deleted);

CREATE POLICY "Users can view their pending landlords" ON public.landlords
  FOR SELECT TO authenticated USING (
    id IN (
      SELECT landlord_id FROM public.reviews
      WHERE user_id = auth.uid()
    )
  );

-- Reviews Table Policies
CREATE POLICY "Admins can update reviews" ON public.reviews
  FOR UPDATE TO public USING (public.is_admin());

CREATE POLICY "Admins can view all reviews" ON public.reviews
  FOR SELECT TO public USING (public.is_admin());

CREATE POLICY "Anyone can insert reviews" ON public.reviews
  FOR INSERT TO public WITH CHECK (user_id IS NULL OR auth.uid() = user_id);

CREATE POLICY "Everyone can view active reviews" ON public.reviews
  FOR SELECT TO public USING (NOT is_deleted);

CREATE POLICY "Users can update own reviews" ON public.reviews
  FOR UPDATE TO public USING (auth.uid() = user_id);

-- 9. Setup Storage Bucket for Verification Files (if storage schema exists)
-- This requires running in a standard Supabase context where storage schema is present
INSERT INTO storage.buckets (id, name, public)
VALUES ('verification-files', 'verification-files', false)
ON CONFLICT (id) DO NOTHING;

-- Storage bucket security policies
CREATE POLICY "Allow authenticated uploads" ON storage.objects
  FOR INSERT TO authenticated WITH CHECK (
    bucket_id = 'verification-files' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );

CREATE POLICY "Allow admin read" ON storage.objects
  FOR SELECT TO public USING (
    bucket_id = 'verification-files' AND
    public.is_admin()
  );

CREATE POLICY "Allow admin delete" ON storage.objects
  FOR DELETE TO public USING (
    bucket_id = 'verification-files' AND
    public.is_admin()
  );

-- 10. Seed Initial Data (Landlords and Reviews)
-- Clearly-fake demo data spanning multiple cities. Note that landlords 4 and 9
-- have properties across MULTIPLE cities (their `cities` array has >1 entry,
-- while `city` holds the primary one).
INSERT INTO public.landlords (id, name, addresses, city, cities, status) OVERRIDING SYSTEM VALUE VALUES
  (1, 'fake landlord 1', ARRAY['123 Forbes Ave'], 'Pittsburgh, PA', ARRAY['Pittsburgh, PA'], 'approved'),
  (2, 'fake landlord 2', ARRAY['456 Fifth Ave'], 'Pittsburgh, PA', ARRAY['Pittsburgh, PA'], 'approved'),
  (3, 'fake landlord 3', ARRAY['100 Market St'], 'Philadelphia, PA', ARRAY['Philadelphia, PA'], 'approved'),
  (4, 'fake regional company', ARRAY['200 High St (Columbus)', '88 Superior Ave (Cleveland)'], 'Columbus, OH', ARRAY['Columbus, OH', 'Cleveland, OH'], 'approved'),
  (5, 'fake landlord 5', ARRAY['600 Congress Ave'], 'Austin, TX', ARRAY['Austin, TX'], 'approved'),
  (6, 'fake landlord 6', ARRAY['1600 Larimer St'], 'Denver, CO', ARRAY['Denver, CO'], 'approved'),
  (7, 'fake landlord 7', ARRAY['9 Beacon St'], 'Boston, MA', ARRAY['Boston, MA'], 'approved'),
  (8, 'fake landlord 8', ARRAY['500 N State St'], 'Chicago, IL', ARRAY['Chicago, IL'], 'approved'),
  (9, 'fake nationwide mgmt', ARRAY['410 Brazos St (Austin)', '900 Champa St (Denver)'], 'Austin, TX', ARRAY['Austin, TX', 'Denver, CO', 'Chicago, IL'], 'approved')
ON CONFLICT (id) DO NOTHING;

-- Set sequence value to avoid collision with manual inserts
SELECT setval('landlords_id_seq', COALESCE((SELECT MAX(id)+1 FROM public.landlords), 1), false);

INSERT INTO public.reviews (id, landlord_id, rating, communication, maintenance, respect, comment, would_rent_again, rent_amount, property_address, verification_status, created_at, updated_at) OVERRIDING SYSTEM VALUE VALUES
  (5, 1, 2, 2, 1, 2, 'Fake review', false, 1200, '456 S Craig St', 'unverified', '2023-07-10 12:00:00+00', '2023-07-10 12:00:00+00'),
  (6, 1, 3, 3, 3, 3, 'Fake review', true, 1350, NULL, 'verified', '2023-09-22 12:00:00+00', '2023-09-22 12:00:00+00'),
  (7, 2, 4, 4, 4, 4, 'Fake review', true, 1500, '234 Neville St', 'verified', '2023-08-18 12:00:00+00', '2023-08-18 12:00:00+00'),
  (8, 3, 4, 5, 4, 4, 'Fake review (Philadelphia)', true, 1500, '100 Market St', 'verified', '2024-08-18 12:00:00+00', '2024-08-18 12:00:00+00'),
  (9, 4, 3, 2, 3, 3, 'Fake review (Columbus unit)', false, 1200, '200 High St', 'unverified', '2024-04-10 12:00:00+00', '2024-04-10 12:00:00+00'),
  (10, 4, 4, 4, 4, 4, 'Fake review (Cleveland unit)', true, 1150, '88 Superior Ave', 'verified', '2024-07-22 12:00:00+00', '2024-07-22 12:00:00+00'),
  (11, 5, 4, 5, 4, 4, 'Fake review (Austin)', true, 1800, '600 Congress Ave', 'verified', '2024-06-18 12:00:00+00', '2024-06-18 12:00:00+00'),
  (12, 9, 4, 4, 4, 4, 'Fake review (Denver unit)', true, 1850, '900 Champa St', 'verified', '2024-06-11 12:00:00+00', '2024-06-11 12:00:00+00')
ON CONFLICT (id) DO NOTHING;

-- Set sequence value to avoid collision with manual inserts
SELECT setval('reviews_id_seq', COALESCE((SELECT MAX(id)+1 FROM public.reviews), 1), false);