-- Database setup script for Rate My Landlord
-- This script sets up the tables, sequences, RLS policies, storage bucket, and seed data.

-- 1. Create admins table
CREATE TABLE IF NOT EXISTS public.admins (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  email text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT admins_pkey PRIMARY KEY (id)
);

-- 2. Create landlords table
CREATE TABLE IF NOT EXISTS public.landlords (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  city text NOT NULL,
  addresses text[] DEFAULT '{}'::text[],
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  is_deleted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT landlords_pkey PRIMARY KEY (id)
);

-- 3. Create reviews table
CREATE TABLE IF NOT EXISTS public.reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  landlord_id bigint NOT NULL,
  user_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  communication integer NOT NULL CHECK (communication >= 1 AND communication <= 5),
  maintenance integer NOT NULL CHECK (maintenance >= 1 AND maintenance <= 5),
  respect integer NOT NULL CHECK (respect >= 1 AND respect <= 5),
  comment text NOT NULL,
  rent_amount numeric,
  property_address text,
  verification_file_url text,
  would_rent_again boolean DEFAULT false,
  verification_status text DEFAULT 'unverified'::text CHECK (verification_status = ANY (ARRAY['unverified'::text, 'pending'::text, 'verified'::text])),
  is_deleted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by_student boolean DEFAULT false,
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_landlord_id_fkey FOREIGN KEY (landlord_id) REFERENCES public.landlords(id) ON DELETE CASCADE,
  CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL
);

-- 4. Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_landlords_city ON public.landlords(city) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS idx_landlords_status ON public.landlords(status) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS idx_reviews_landlord_id ON public.reviews(landlord_id) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS idx_reviews_user_id ON public.reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_verification_status ON public.reviews(verification_status) WHERE NOT is_deleted;

-- 5. Trigger for updated_at on reviews table
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trigger_reviews_updated_at
  BEFORE UPDATE ON public.reviews
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_updated_at();

-- 6. Helper function to check if the current user is an admin
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean SECURITY DEFINER AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.admins
    WHERE email = auth.jwt() ->> 'email'
  );
END;
$$ LANGUAGE plpgsql;

-- 7. Enable Row Level Security (RLS)
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.landlords ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- 8. Row Level Security policies

-- Admins Table Policies
CREATE POLICY "Anyone can view admins" ON public.admins
  FOR SELECT TO public USING (true);

-- Landlords Table Policies
CREATE POLICY "Admins can update landlords" ON public.landlords
  FOR UPDATE TO public USING (public.is_admin());

CREATE POLICY "Admins can view all landlords" ON public.landlords
  FOR SELECT TO public USING (public.is_admin());

CREATE POLICY "Authenticated users can insert landlords" ON public.landlords
  FOR INSERT TO public WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Everyone can view approved landlords" ON public.landlords
  FOR SELECT TO public USING (status = 'approved' AND NOT is_deleted);

CREATE POLICY "Users can view their pending landlords" ON public.landlords
  FOR SELECT TO authenticated USING (
    id IN (
      SELECT landlord_id FROM public.reviews
      WHERE user_id = auth.uid()
    )
  );

-- Reviews Table Policies
CREATE POLICY "Admins can update reviews" ON public.reviews
  FOR UPDATE TO public USING (public.is_admin());

CREATE POLICY "Admins can view all reviews" ON public.reviews
  FOR SELECT TO public USING (public.is_admin());

CREATE POLICY "Anyone can insert reviews" ON public.reviews
  FOR INSERT TO public WITH CHECK (user_id IS NULL OR auth.uid() = user_id);

CREATE POLICY "Everyone can view active reviews" ON public.reviews
  FOR SELECT TO public USING (NOT is_deleted);

CREATE POLICY "Users can update own reviews" ON public.reviews
  FOR UPDATE TO public USING (auth.uid() = user_id);

-- 9. Setup Storage Bucket for Verification Files (if storage schema exists)
-- This requires running in a standard Supabase context where storage schema is present
INSERT INTO storage.buckets (id, name, public)
VALUES ('verification-files', 'verification-files', false)
ON CONFLICT (id) DO NOTHING;

-- Storage bucket security policies
CREATE POLICY "Allow authenticated uploads" ON storage.objects
  FOR INSERT TO authenticated WITH CHECK (
    bucket_id = 'verification-files' AND
    (storage.foldername(name))[1] = auth.uid()::text
  );

CREATE POLICY "Allow admin read" ON storage.objects
  FOR SELECT TO public USING (
    bucket_id = 'verification-files' AND
    public.is_admin()
  );

CREATE POLICY "Allow admin delete" ON storage.objects
  FOR DELETE TO public USING (
    bucket_id = 'verification-files' AND
    public.is_admin()
  );

-- 10. Seed Initial Data (Landlords and Reviews)
INSERT INTO public.landlords (id, name, addresses, city, status) OVERRIDING SYSTEM VALUE VALUES
  (1, 'fake landlord 1', ARRAY['123 Forbes Ave'], 'Pittsburgh', 'approved'),
  (2, 'fake landlord 2', ARRAY['456 Fifth Ave'], 'Pittsburgh', 'approved'),
  (4, 'John C.R. Kelly Realty', '{}', 'Pittsburgh', 'approved'),
  (5, 'Walnut Capital', '{}', 'Pittsburgh', 'approved'),
  (6, 'Lobos Management', '{}', 'Pittsburgh', 'approved'),
  (7, 'Bob Eckenrode', '{}', 'Pittsburgh', 'approved'),
  (8, 'TMK Properties', '{}', 'Pittsburgh', 'approved'),
  (9, 'Mozart Management', '{}', 'Pittsburgh', 'approved'),
  (10, 'Palmieri Property Management', '{}', 'Pittsburgh', 'approved')
ON CONFLICT (id) DO NOTHING;

-- Set sequence value to avoid collision with manual inserts
SELECT setval('landlords_id_seq', COALESCE((SELECT MAX(id)+1 FROM public.landlords), 1), false);

INSERT INTO public.reviews (id, landlord_id, rating, communication, maintenance, respect, comment, would_rent_again, rent_amount, property_address, verification_status, created_at, updated_at) OVERRIDING SYSTEM VALUE VALUES
  (5, 1, 2, 2, 1, 2, 'Fake review', false, 1200, '456 S Craig St', 'unverified', '2023-07-10 12:00:00+00', '2023-07-10 12:00:00+00'),
  (6, 1, 3, 3, 3, 3, 'Fake review', true, 1350, NULL, 'verified', '2023-09-22 12:00:00+00', '2023-09-22 12:00:00+00'),
  (7, 1, 1, 1, 2, 1, 'Fake review', false, NULL, '789 Bellefonte St', 'pending', '2023-06-05 12:00:00+00', '2023-06-05 12:00:00+00'),
  (8, 2, 4, 4, 4, 4, 'Fake review', true, 1500, '234 Neville St', 'verified', '2023-08-18 12:00:00+00', '2023-08-18 12:00:00+00'),
  (9, 2, 3, 4, 3, 3, 'Fake review', true, 1400, NULL, 'unverified', '2023-10-01 12:00:00+00', '2023-10-01 12:00:00+00'),
  (10, 2, 5, 5, 5, 4, 'Fake review', true, 1600, NULL, 'verified', '2023-09-15 12:00:00+00', '2023-09-15 12:00:00+00')
ON CONFLICT (id) DO NOTHING;

-- Set sequence value to avoid collision with manual inserts
SELECT setval('reviews_id_seq', COALESCE((SELECT MAX(id)+1 FROM public.reviews), 1), false);